#!/bin/bash -x

KEEP_ALIVE=false
waitforever() {
    while ${KEEP_ALIVE}; 
    do
      sleep 10
      echo "Still alive"
    done
}

_stop() {
  echo "Stopping RAW_EXEC_PROCESS"
  echo "finished"
  KEEP_ALIVE=false
  exit
}

echo "Trapping SIGINT, SIGTERM and SIGKILL"
trap _stop SIGINT
trap _stop SIGTERM

echo "I do nothing, but wait.."
KEEP_ALIVE=true
waitforever


