---
platform: ubuntu

#########################################
# Kubernetes Deployment Specification   #
#########################################

#Kubernetes Version to be used for deployment
#Accepted Entries (Valid Kubernetes Version): default:1.6.3
#Accepted Entries (Valid Weave Version): default:1.9.4

k8s_version: 1.7.8 
weave_version: 2.0.4

#list of kubernetes versions released.
#do not tamper the list unless you know
#what you are doing...

k8s_version_list:
  - 1.7.5
  - 1.7.8

weave_version_list:
  - 1.9.4
  - 2.0.4 

#######################################
#     OpenEBS deployment type         #
#######################################
#Option to specify OpenEBS deployment type
# It can be either kubectl or helm based installation

openebs_deploy: helm


#########################################
# OpenEBS Deployment Specifications     #
#########################################

#Mode of openEBS deployment 
#Accepted Entries (dedicated, hyperconverged): default:hyperconverged 

deployment_mode: hyperconverged 

#Option specifically for vagrant VMs
#Accepted Entries(true, false): default:false

is_vagrant_vm: true

#########################################
# Ansible Runtime Specifications        #
#########################################

#Option to run the sample demo of OpenEBS
#Accepted Entries(true, false): default:true

run_demo: true

#Option to setup Ansible Runtime Analysis playbook recorder
#Accepted Entries(true, false): default:true

ara_setup: true 

#Option to enable slack notifications to specified channel
#Accepted Entries(true, false): default:true

slack_notify: true

#########################################
# OpenEBS Test Specifications           #
#########################################

#Option to run cleanup functions in tests
#Accepted Entries(true, false): default:true

clean: true

#Option to capture logs for test runs
#Accepted Entries(true, false): default:true
logging: true

#########################################
# OpenEBS CI Specifications             #
#########################################

#Option to select type of CI build
#Accepted Entries(quick, normal): default:normal
#quick build uses preconfigured VMs, 
#normal builds upon vanilla VMs

build_type: normal

