apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-admin

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: casTemplate
  namespace: default
subjects:
- kind: ServiceAccount
  name: cluster-admin
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
