---
- name: Create Volume
  shell: source ~/.profile; maya vsm-create -name={{openebs_vol_name}} -size={{openebs_vol_size}}
  args:
    executable: /bin/bash
  delegate_to: "{{groups['openebs-mayamaster'].0}}" 

- name: Get Volume Info
  shell: source ~/.profile; maya vsm-stats {{openebs_vol_name}}
  args:
    executable: /bin/bash
  register: result
  until: "'Online' in result.stdout"
  delay: 60
  retries: 10
  delegate_to: "{{groups['openebs-mayamaster'].0}}" 

- name: Fetch Target Portal
  shell: "echo {{result.stdout_lines[4]}} | grep -i 'portal' | awk '{print $2}'"
  register: result

- name: Update Target Portal
  set_fact:
    openebs_target_portal: "{{result.stdout}}"
  delegate_to: "{{groups['openebs-mayamaster'].0}}"
  delegate_facts: true
