---
- name: Create Volume
  shell: source ~/.profile; maya vsm-create -name={{openebs_vol_name}} -size={{openebs_vol_size}}
  args:
    executable: /bin/bash
  when: openebs_vol_size|int >=1
  delegate_to: "{{hostvars[groups['openebs-mayamaster'][0]]['ansible_ssh_host']}}"

- name: Get Volume Info
  shell: source ~/.profile; maya vsm-stats {{openebs_vol_name}}
  args:
    executable: /bin/bash
  register: result
  until: "'Portal' in result.stdout"
  delay: 10
  retries: 3
  delegate_to: "{{hostvars[groups['openebs-mayamaster'][0]]['ansible_ssh_host']}}"

- name: Fetch Target Portal
  shell: "echo {{result.stdout_lines[4]}} | grep -i 'portal' | awk '{print $2}'"
  register: result

- name: Update Target Portal
  set_fact:
    openebs_target_portal: "{{result.stdout}}"
