#!/bin/bash
set -e

IMAGEID=$( sudo docker images -q openebs/sonar-operator:ci )

if [ ! -z "${DNAME}" ] && [ ! -z "${DPASS}" ]; 
then 
  sudo docker login -u "${DNAME}" -p "${DPASS}"; 
  sudo docker push openebs/sonar-operator:ci ; 
  if [ ! -z "${TRAVIS_TAG}" ] ; 
  then
    #Push the release tag image to docker hub repository
    #When a git hub is tagged with a release, the travis will 
    #hold the release tag in env TRAVIS_TAG
    sudo docker tag ${IMAGEID} openebs/sonar-operator:${TRAVIS_TAG}
    sudo docker push openebs/sonar-operator:${TRAVIS_TAG}; 
    sudo docker tag ${IMAGEID} openebs/sonar-operator:latest
    sudo docker push openebs/sonar-operator:latest; 
  fi;
else
  echo "No docker credentials provided. Skip uploading openebs/sonar-operator:ci to docker hub"; 
fi;
