---
apiVersion: v1
kind: ConfigMap
metadata:
  name: basic
data:
 basic-rw : |-
     [global]
     directory=/datadir

     [basic-fio]
     rw=write
     bs=8k
     time_based=1
     runtime=60
     verify=crc32c
---
apiVersion: batch/v1
kind: Job
metadata:
  name: fio
spec:
  template:
    metadata:
      name: fio
    spec:
      restartPolicy: Never
      containers:
      - name: perfrunner
        image: openebs/tests-fio
        command: ["/bin/bash"]
        args: ["-c", "./fio_runner.sh --size 1g; exit 0"]
        volumeMounts:
           - mountPath: /datadir
             name: demo-vol1
           - mountPath: templates/file/basic-rw
             subPath: basic-rw
             name: basic-configmap
        tty: true
      volumes:
      - name: demo-vol1
        persistentVolumeClaim:
          claimName: demo-vol1-claim
      - name: basic-configmap
        configMap:
          name: basic
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo-vol1-claim
spec:
  storageClassName: openebs-standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "5G"
