---
- hosts: openebs-mayamaster
  
  vars_files:
    - variables/vars.yml #Import variables from external file.

  tasks:
    - name: Set flag
      set_fact:
        flag: "Succeeded"

    - name: Create Volume
      shell: source ~/.profile; maya vsm-create -name={{openebs_vol_name}} -size={{openebs_vol_size}}
      args:
        executable: /bin/bash
      when: openebs_vol_size|int >=1
      register: result
      ignore_errors: yes

    - name: Set flag
      set_fact:
        flag: "failed"
      when: result|failed

    - name: Create Volume
      shell: source ~/.profile; maya vsm-create -name={{openebs_vol_name}}
      args:
        executable: /bin/bash
      when: openebs_vol_size|int <= 0
      register: result
      ignore_errors: yes
  
    - name: Set flag
      set_fact: 
        flag: "failed"
      when: result|failed

    - name: Get Volume Info
      shell: source ~/.profile; maya vsm-stats {{openebs_vol_name}}
      args:
        executable: /bin/bash
      register: result
      until: "'Portal' in result.stdout"
      delay: 10
      retries: 3
      ignore_errors: yes

    - name: Set flag
      set_fact:
        flag: "failed"
      when: result|failed

    - name: Query Target Portal
      shell: "echo {{result.stdout_lines[4]}} | grep -i 'portal' | awk '{print $2}'"
      register: result
      ignore_errors: yes

    - name: Set flag
      set_fact:
        flag: "failed"
      when: result|failed

    - name: Update Target Portal
      set_fact:
        openebs_target_portal: "{{result.stdout}}"
      ignore_errors: yes

    - name: Set flag
      set_fact:
        flag: "failed"
      when: result|failed
   
    - name: Results
      fail: 
        msg: "The tests have failed because of errors."
      when: flag == "failed"
