---
- hosts: openebs-mayamaster
  
  vars_files:
    - variables/vars.yml

  tasks:
    - name: Set flag
      set_fact:
        flag: "Succeeded"

    - name: Update INI file
      ini_file:
        path: /etc/mayaserver/orchprovider/nomad_global.INI
        section: datacenter "dc1"
        option: cn-network-cidr
        value: "{{openebs_cn_network_cidr}}"
        backup: yes
      become: true
      register: result          
      ignore_errors: yes

    - name: Set flag
      set_fact:      
        flag: "failed"
      when: result|failed

    - name: Update INI file
      ini_file:
        path: /etc/mayaserver/orchprovider/nomad_global.INI
        section: datacenter "dc1"
        option: cn-interface
        value: "{{openebs_cn_interface}}"
        backup: yes
      become: true
      register: result
      notify: Restart M_APIServer
      ignore_errors: yes

    - name: Set flag
      set_fact: 
        flag: "failed"
      when: result|failed

  handlers:
        
    - name: Restart M_APIServer
      service:
        name: m-apiserver
        state: started
        enabled: yes
      register: result
      ignore_errors: yes

    - name: Set flag
      set_fact:
        flag: "failed"
      when: result|failed

    - name: Results
      fail:
        msg: "The tests have failed because of errors."
      when: flag == "failed"

