---
- name: Setup Maya      
  command: maya setup-omm -self-ip="{{hostvars[inventory_hostname]['ansible_ssh_host']}}"

- name: Update INI file
  ini_file:
    path: /etc/mayaserver/orchprovider/nomad_global.INI
    section: datacenter "dc1"
    option: cn-network-cidr
    value: "{{cn_network_cidr}}"
    backup: yes
  become: true

- name: Update INI file
  ini_file:
    path: /etc/mayaserver/orchprovider/nomad_global.INI
    section: datacenter "dc1"
    option: cn-interface
    value: "{{cn_interface}}"
    backup: yes
  become: true
  register: result
  notify: Restart M_APIServer
