apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  serviceAccountName: super-admin
  containers:
  - name: ubuntu
    image: ubuntu:latest
    # spin & wait forever
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
