---
#- hosts: localhost

#  pre_tasks:
#  - name: Generate Inventory
#    script: generate-inventory.py ../inventory/machine.in

- hosts: openebs-mayamaster

  roles:
    - master
    - {role: vagrant, when: is_vagrant_vm | bool} 

- hosts: openebs-mayahosts

  roles:
    - hosts
    - {role: vagrant, when: is_vagrant_vm | bool}

- hosts: localhost  
  roles:
    - localhost 
    - volume
    - fio

