---
- name: Install APT Packages 
  apt: 
    name: "{{item}}" 
    state: present
  with_items: "{{deb_local_packages}}"
  become: true
  delegate_to: 127.0.0.1

- name: Install PIP Packages
  pip: 
    name: "{{ item }}" 
    state: present
  with_items: "{{ pip_local_packages }}"
  become: true
  delegate_to: 127.0.0.1
