---
- name: Generate Inventory
  command: "python {{inventory_script_path}}/generate-inventory.py {{inventory_input_path}}/machines.in"
  delegate_to: 127.0.0.1

- name: Sync Inventory
  meta: refresh_inventory

